; Drush Make file for IBP
;
; NOTE: this make file utilizes a patch for drush make
; that allows downloading of subtrees of git repos.
; http://drupal.org/node/1074748
;

; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.26"

; Modules
projects[admin_menu][version] = "1.8"

projects[advanced_help][version] = "1.2"

projects[auto_nodetitle][version] = "1.2"

projects[automenu][version] = "2.x-dev"

projects[backup_migrate][version] = "2.6"

projects[biblio][version] = "1.18"

projects[ctools][version] = "1.9"

projects[calendar][version] = "2.x-dev"

projects[css_names][version] = "1.0"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Modules
projects[cck][version] = "2.9"

projects[content_profile][version] = "1.0"

projects[content_taxonomy][version] = "1.0-rc2"

projects[countries_api][version] = "1.2"

projects[date][version] = "2.9"

projects[drupalchat][version] = "2.0-beta11"

projects[ed_readmore][version] = "5.0"

projects[faq][version] = "1.13"

projects[filefield][version] = "3.10"

projects[filefield_track][version] = "1.2"

projects[fpa][version] = "2.4"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[getid3][download][type] = ""
libraries[getid3][download][url] = ""
libraries[getid3][directory_name] = "getid3"
libraries[getid3][type] = "library"

; Modules
projects[globalredirect][version] = "1.5"

projects[google_analytics][version] = "3.3"

projects[i18n][version] = "1.10"

projects[i18nmenu_node][version] = "1.2"

projects[i18nviews][version] = "2.0"

projects[imageapi][version] = "1.10"

projects[imagecache][version] = "2.0-rc1"

projects[imagecache_profiles][version] = "1.3"

projects[imagefield][version] = "3.10"

projects[imce][version] = "2.3"

projects[jquery_ui][version] = "1.5"

projects[jquery_update][version] = "2.0-alpha1"

projects[l10n_update][version] = "1.0-beta3"

projects[lang_dropdown][version] = "1.7"

projects[languageicons][version] = "2.1"

projects[ldap_integration][version] = "1.0-beta3"

projects[libraries][version] = "1.0"

projects[link][version] = "2.9"

projects[location][version] = "3.2"

projects[menu_block][version] = "2.4"

projects[menu_per_role][version] = "1.11"

projects[messaging][version] = "2.4"

projects[mimemail][version] = "1.1"

projects[multiblock][version] = "1.4"

projects[node_convert][version] = "1.7"

projects[noreqnewpass][version] = "2.0"

projects[notifications][version] = "2.3"

projects[panels][version] = "3.10"

projects[pathauto][version] = "1.6"

projects[permissions_api][version] = "3.1"

projects[phone][version] = "2.18"

projects[potx][version] = "3.3"

projects[revision_deletion][version] = "1.0-rc2"

projects[role_delegation][version] = "1.4"

projects[rules][version] = "1.5"

projects[site_map][version] = "2.2"

projects[stringoverrides][version] = "1.8"

projects[subpath_alias][version] = "1.1"

projects[taxonomy_menu][version] = "2.9"

projects[taxonomy_menu_trails][version] = "1.4"

projects[token][version] = "1.19"

projects[translation_overview][version] = "2.4"

projects[translation_table][version] = "1.4"

projects[transliteration][version] = "3.1"

projects[upload_replace][version] = "1.2"

projects[url_alter][version] = "1.2"

projects[user_relationships][version] = "1.3"

projects[views][version] = "2.16"

projects[views_or][version] = "1.x-dev"

projects[webform][version] = "3.18"

projects[xmlsitemap][version] = "2.0-rc1"

; Themes
projects[zen][version] = "2.1"

projects[zeropoint][version] = "1.12"

; Custom Modules
; INSTALL THESE MODULES FROM GIT
;; clade
;projects[clade][download][type] = git
;projects[clade][download][url] = git@github.com:iPlantCollaborativeOpenSource/IBP.git
;projects[clade][download][subtree] = modules/clade
;projects[clade][type] = module
;
;; ibphelper
;projects[ibphelper][download][type] = git
;projects[ibphelper][download][url] = git@github.com:iPlantCollaborativeOpenSource/IBP.git
;projects[ibphelper][download][subtree] = modules/ibphelper
;projects[ibphelper][type] = module
;
;; ibp_projects
;projects [ibp_projects][download][type] = git
;projects [ibp_projects][download][url] = git@github.com:iPlantCollaborativeOpenSource/IBP.git
;projects [ibp_projects][download][subtree] = modules ibp_projects
;projects [ibp_projects][type] = module
;
;; ibp_variety_releases
;projects[ibp_variety_releases][download][type] = git
;projects[ibp_variety_releases][download][url] = git@github.com:iPlantCollaborativeOpenSource/IBP.git
;projects[ibp_variety_releases][download][subtree] = modules/ibp_variety_releases
;projects[ibp_variety_releases][type] = module
;
;; jit
;projects[jit][download][type] = git
;projects[jit][download][url] = git@github.com:iPlantCollaborativeOpenSource/IBP.git
;projects[jit][download][subtree] = modules/jit
;projects[jit][type] = module
;
;; teaser_comments
;projects[teaser_comments][download][type] = git
;projects[teaser_comments][download][url] = git@github.com:iPlantCollaborativeOpenSource/IBP.git
;projects[teaser_comments][download][subtree] = modules/teaser_comments
;projects[teaser_comments][type] = module
;
;; ibp_theme
;projects[teaser_comments][download][type] = git
;projects[teaser_comments][download][url] = git@github.com:iPlantCollaborativeOpenSource/IBP.git
;projects[teaser_comments][download][subtree] = themes/ibp_theme
;projects[teaser_comments][type] = theme

; Libraries

; JIT
libraries[jit][download][type] = get
libraries[jit][download][url] = http://thejit.org/downloads/Jit-2.0.1.zip
libraries[jit][type] = library

;ckeditor
; use drush command `drush ckeditor-download`

; getid3
; use drush command `drush getid3-download`
;libraries[getid3][download][type] = get
;libraries[getid3][download][url] = http://downloads.sourceforge.net/project/getid3/getID3%28%29%201.x/1.8.5/getid3-1.8.5-20110218.zip
;libraries[getid3][type] = library

; iphone_check
libraries[iphone_check][download][type] = git
libraries[iphone_check][download][url] = https://github.com/tdreyno/iphone-style-checkboxes.git
libraries[iphone_check][type] = library

; jquery-ui
libraries[jquery_ui][download][type] = get
libraries[jquery_ui][download][url] = http://jquery-ui.googlecode.com/files/jquery-ui-1.7.3.zip
libraries[jquery_ui][download][sha1] = 7707d98bce0c90b06fdd3cd3acbf53c46a2aceb5
libraries[jquery_ui][destination] = modules/jquery_ui
libraries[jquery_ui][directory_name] = jquery.ui
libraries[jquery_ui][type] = library

; jquery_autocomplete
libraries[jquery_autocomplete][download][type] = git
libraries[jquery_autocomplete][download][url] = https://github.com/agarzola/jQueryAutocompletePlugin.git
libraries[jquery_autocomplete][type] = library

; yui for drupalchat
libraries[yui][download][type] = get
libraries[yui][download][url] = http://yui.zenfs.com/releases/yui3/yui_3.5.1.zip
libraries[yui][type] = library