<p>
	New comment by [comment_author:content-profile-profile-profile_first_name] [comment_author:content-profile-profile-profile_last_name]:
	<br>[comment:comment-body]</p>
<p>
	Original [node:type-name] by [node_author:content-profile-profile-profile_first_name] [node_author:content-profile-profile-profile_last_name]:
	<br>
	<?php echo $node->teaser; ?></p>
<br>
<br>
<p>
	Read more on [:global:site-name]:
	<a href="[node:node-url]">[node:node-url]</a>
</p>
<p>
	Manage your subscriptions for the [node:clade-name] Community:
	<a href="[node:clade-subscriptions-url]">[node:clade-subscriptions-url]</a>
</p>