<p>
	New update for [node:type-name] by [user:content-profile-profile-profile_first_name] [user:content-profile-profile-profile_last_name]:
	<br>
	<?php echo $node->teaser; ?></p>
<br>
<br>
<p>
	Read more on [:global:site-name]:
	<a href="[node:node-url]">[node:node-url]</a>
</p>
<p>
	Manage your subscriptions for the [node:clade-name] Community:
	<a href="[node:clade-subscriptions-url]">[node:clade-subscriptions-url]</a>
</p>