<?php

function ibp_projects_node_info() {
  return array(
		'ibp_project' => array(
			'name' => t('IBP Project'),
			'module' => 'ibp_projects',
			'description' => 'A project within a crop or crops.',
			'has_title' => TRUE,
			'title_label' => 'Project Name',
			'has_body' => TRUE,
			'body_label' => 'Description',
		),
	);
}

function ibp_projects_perm() {
  return array(
			'create ibp_project',
			'edit own ibp_project',
			'edit any ibp_project',
			'delete ibp_project',
		);
}

/**
 * Implementation of hook_access()
 */
function ibp_projects_access($op, $node, $account) {
  global $user;
  switch ($op) {
  case 'view' :
  	return TRUE;
  case 'create' :
  	return user_access('create ibp_project');
  case 'update' :
  	if ($user->uid == $node->uid) {
  		return user_access('edit own ibp_project');
  	} else {
  		return user_access('edit any ibp_project');
  	}
  case 'delete' :
  	return user_access('delete ibp_project');
  }
}


function ibp_projects_form(&$node, $form_state) {
	$type = node_get_types('type', $node->type);
	$form = array();
	
	$form['title'] = array(
		'#title' => $type->title_label,
		'#type' => 'textfield',
		'#required' => TRUE,
		'#default_value' => $node->nid ? $node->title : $form_state['values']['title'],
	);
	
	$form['body'] = array(
		'#title' => $type->body_label,
		'#type' => 'textarea',
		'#required' => TRUE,
		'#default_value' => $node->nid ? $node->body : $form_state['values']['body'],
	);
	
	return $form;
}

function ibp_projects_clade($op, $clade, $args=array()) {
	if ($op == 'clade insert') {
		$clade_menu = menu_get_item("clade/$clade->tid");
		$menu = array(
			'menu_name' => 'primary-links',
			'plid' => $clade_menu['mlid'],
			'router_path' => 'clade/%/projects',
			'link_path' => "clade/$clade->tid/projects",
			'link_title' => $clade->name . ' projects',
			'weight' => 11,
			);
		menu_link_save($menu);
	}
	// TODO delete?
}

function ibp_projects_clade_details_items($clade) {
	$items = array(
	'project_page' => array(
		'data' => l(t('Projects'), "clade/$clade->tid/projects"),
		'data-sort' => 3,
		'class' => 'clade-details-item',
		),
	);
	if (user_access('create ibp_project')) {
		$items['add_project_page'] = array(
			'data' => l(t('Add a new Project'), "node/add/ibp-project", array('query' => array('clades' => $clade->tid))),
			'data-sort' => 12,
			'class' => 'clade-details-item',
		);
	}
	return $items;
}


function ibp_projects_views_api() {
  return array('api' => 2.0);
}