<?php
/**
 * Copyright (c) 2010, iPlant Collaborative, University of Arizona, Cold Spring Harbor Laboratories, University of Texas at Austin
 * This software is licensed under the CC-GNU GPL version 2.0 or later.
 * License: http://creativecommons.org/licenses/GPL/2.0/
 */
 
function jit_spacetree_install() {
	$weight = db_result(db_query("SELECT weight FROM {system} WHERE name = 'jit'"));
	db_query("UPDATE {system} SET weight = %d WHERE name = 'jit_spacetree'", $weight + 1);
}