<?php
/**
 * Copyright (c) 2010, iPlant Collaborative, University of Arizona, Cold Spring Harbor Laboratories, University of Texas at Austin
 * This software is licensed under the CC-GNU GPL version 2.0 or later.
 * License: http://creativecommons.org/licenses/GPL/2.0/
 */

function jit_init() {
}

function jit_perm() {
	return array(
		'administer jit',
		);
}

function jit_menu() {
	$items = array();
	
	$items['admin/settings/jit'] = array(
			'page callback' => 'drupal_get_form',
			'page arguments' => array('jit_admin_form'),
			'title' => t('Javascript InfoVis Toolkit (JIT)'),
			'access arguments' => array('administer jit'),
		);
	
	return $items;
}

/*
 * Adds all necessary js to request
 */
function jit_resources() {
	if ( strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') ) {
		//preprocess causes js errors
		drupal_add_js(libraries_get_path('jit') .'/Extras/excanvas.js');
	}
	
	if (variable_get('jit_enable_debug', 0)) {
		drupal_add_js(libraries_get_path('jit') . '/jit.js');
	} else {
		drupal_add_js(libraries_get_path('jit') . '/jit-yc.js');
	}
	
	if (module_exists('jquery_ui')) {
		jquery_ui_add('effects.core');
	}

	drupal_add_js(drupal_get_path('module', 'jit') .'/js/drupal-jit.js');
	drupal_add_css(drupal_get_path('module', 'jit') .'/css/jit.css');
}

function jit_admin_form() {
	$form = array();
	
	$form['jit_enable_debug'] = array(
		'#type' => 'checkbox',
		'#title' => t('Enable JIT Example Pages'),
		'#description' => t('JIT Visualizations provide an example page (usually at `jit/[viz name]/debug`) that showcase the options available for each visualization.  This option should probably be disabled in production environments.'),
		'#default_value' => variable_get('jit_enable_debug', 0),
		);
	
	$form['#submit'] = array('jit_admin_form_submit');
	
	return system_settings_form($form);
}

function jit_admin_form_submit($form, &$form_state) {
	menu_router_build(true);
	menu_cache_clear_all();
}

function jit_theme($existing, $typs, $theme, $path) {
	return array(
		'jit_on_before_compute' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-before-compute'
			),
		'jit_on_after_compute' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-after-compute'
			),
		'jit_on_create_label' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-create-label'
			),
		'jit_on_place_label' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-place-label'
			),
		'jit_on_complete' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-complete'
			),
		'jit_on_before_plot_line' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-before-plot-line'
			),
		'jit_on_after_plot_line' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-after-plot-line'
			),
		'jit_on_before_plot_node' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-before-plot-node'
			),
		'jit_on_after_plot_node' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-on-after-plot-node'
			),
		'jit_request' => array(
				'arguments' => array(
					'tree_id' => null,
					),
				'template' => 'theme/jit-request'
			),
		);
}